export const initialCards = [
  // Black Cards (Questions)
  { text: "Why can't I sleep at night?", type: "black", pick: 1 },
  { text: "I got 99 problems but _ ain't one.", type: "black", pick: 1 },
  { text: "What's a girl's best friend?", type: "black", pick: 1 },
  { text: "What's that smell?", type: "black", pick: 1 },
  { text: "This is the way the world ends. Not with a bang but with _.", type: "black", pick: 1 },
  { text: "What is Batman's guilty pleasure?", type: "black", pick: 1 },
  { text: "TSA guidelines now prohibit _ on airplanes.", type: "black", pick: 1 },
  { text: "What ended my last relationship?", type: "black", pick: 1 },
  { text: "MTV's new reality show features eight washed-up celebrities living with _.", type: "black", pick: 1 },
  { text: "I drink to forget _.", type: "black", pick: 1 },
  { text: "I'm sorry, Professor, but I couldn't complete my homework because of _.", type: "black", pick: 1 },
  { text: "Alternative medicine is now embracing the curative powers of _.", type: "black", pick: 1 },
  { text: "What's the next Happy Meal® toy?", type: "black", pick: 1 },
  { text: "What's the most emo?", type: "black", pick: 1 },
  { text: "During his midlife crisis, my dad got into _.", type: "black", pick: 1 },

  // White Cards (Answers)
  { text: "Coat hanger abortions.", type: "white" },
  { text: "Man meat.", type: "white" },
  { text: "Autocannibalism.", type: "white" },
  { text: "Vigorous jazz hands.", type: "white" },
  { text: "Flightless birds.", type: "white" },
  { text: "Pictures of boobs.", type: "white" },
  { text: "Doing the right thing.", type: "white" },
  { text: "The violation of our most basic human rights.", type: "white" },
  { text: "Viagra®.", type: "white" },
  { text: "Self-loathing.", type: "white" },
  { text: "Spectacular abs.", type: "white" },
  { text: "A balanced breakfast.", type: "white" },
  { text: "Roofies.", type: "white" },
  { text: "Concealing a boner.", type: "white" },
  { text: "Amputees.", type: "white" },
  { text: "The Big Bang.", type: "white" },
  { text: "Former President George W. Bush.", type: "white" },
  { text: "The Rev. Dr. Martin Luther King, Jr.", type: "white" },
  { text: "Smegma.", type: "white" },
  { text: "Being marginalized.", type: "white" },
  { text: "Cuddling.", type: "white" },
  { text: "Laying an egg.", type: "white" },
  { text: "The Pope.", type: "white" },
  { text: "Aaron Burr.", type: "white" },
  { text: "Genghis Khan.", type: "white" },
  { text: "The south.", type: "white" },
  { text: "The guys from Queer Eye.", type: "white" },
  { text: "My humps.", type: "white" },
  { text: "The hardworking Mexican.", type: "white" },
  { text: "Agriculture.", type: "white" },
];
