export const initialCards = [
  // Black Cards (Questions)
  { text: "Why can't I sleep at night?", type: "black", pick: 1 },
  { text: "I got 99 problems but _ ain't one.", type: "black", pick: 1 },
  { text: "What's a girl's best friend?", type: "black", pick: 1 },
  { text: "What's that smell?", type: "black", pick: 1 },
  { text: "This is the way the world ends. Not with a bang but with _.", type: "black", pick: 1 },
  { text: "What is Batman's guilty pleasure?", type: "black", pick: 1 },
  { text: "TSA guidelines now prohibit _ on airplanes.", type: "black", pick: 1 },
  { text: "What ended my last relationship?", type: "black", pick: 1 },
  { text: "MTV's new reality show features eight washed-up celebrities living with _.", type: "black", pick: 1 },
  { text: "I drink to forget _.", type: "black", pick: 1 },
  { text: "I'm sorry, Professor, but I couldn't complete my homework because of _.", type: "black", pick: 1 },
  { text: "Alternative medicine is now embracing the curative powers of _.", type: "black", pick: 1 },
  { text: "What's the next Happy Meal® toy?", type: "black", pick: 1 },
  { text: "What's the most emo?", type: "black", pick: 1 },
  { text: "During his midlife crisis, my dad got into _.", type: "black", pick: 1 },
  { text: "What's the next scandalous thing Donald Trump will tweet?", type: "black", pick: 1 },
  { text: "In the new Among Us update, the Impostor can now use _ to kill.", type: "black", pick: 1 },
  { text: "What was the real reason Jeffrey Epstein didn't kill himself?", type: "black", pick: 1 },
  { text: "Adolf Hitler's secret hobby was actually _.", type: "black", pick: 1 },
  { text: "The most erotic thing about a French accent is _.", type: "black", pick: 1 },

  // White Cards (Answers)
  { text: "Coat hanger abortions.", type: "white" },
  { text: "Man meat.", type: "white" },
  { text: "Autocannibalism.", type: "white" },
  { text: "Vigorous jazz hands.", type: "white" },
  { text: "Flightless birds.", type: "white" },
  { text: "Pictures of boobs.", type: "white" },
  { text: "Doing the right thing.", type: "white" },
  { text: "The violation of our most basic human rights.", type: "white" },
  { text: "Viagra®.", type: "white" },
  { text: "Self-loathing.", type: "white" },
  { text: "Spectacular abs.", type: "white" },
  { text: "A balanced breakfast.", type: "white" },
  { text: "Roofies.", type: "white" },
  { text: "Concealing a boner.", type: "white" },
  { text: "Amputees.", type: "white" },
  { text: "The Big Bang.", type: "white" },
  { text: "Former President George W. Bush.", type: "white" },
  { text: "The Rev. Dr. Martin Luther King, Jr.", type: "white" },
  { text: "Smegma.", type: "white" },
  { text: "Being marginalized.", type: "white" },
  { text: "Cuddling.", type: "white" },
  { text: "Laying an egg.", type: "white" },
  { text: "The Pope.", type: "white" },
  { text: "Aaron Burr.", type: "white" },
  { text: "Genghis Khan.", type: "white" },
  { text: "The south.", type: "white" },
  { text: "The guys from Queer Eye.", type: "white" },
  { text: "My humps.", type: "white" },
  { text: "The hardworking Mexican.", type: "white" },
  { text: "Agriculture.", type: "white" },
  { text: "Donald Trump's majestic golden mane.", type: "white" },
  { text: "A suspiciously shaped Among Us character.", type: "white" },
  { text: "Jeffrey Epstein's flight logs.", type: "white" },
  { text: "Adolf Hitler's missing testicle.", type: "white" },
  { text: "A thick, incomprehensible Scottish accent.", type: "white" },
  { text: "Unprotected sex with a stranger.", type: "white" },
  { text: "Being the Impostor and venting in front of everyone.", type: "white" },
  { text: "Donald Trump's tiny, tiny hands.", type: "white" },
  { text: "A sexy German accent.", type: "white" },
  { text: "The ghost of Jeffrey Epstein.", type: "white" },
  { text: "Unexpectedly getting an erection during a job interview.", type: "white" },
  { text: "Aggressive sexual healing.", type: "white" },
  { text: "Hiding in the vents like a little sussy baka.", type: "white" },
  { text: "A list of people who definitely weren't on that island.", type: "white" },
  { text: "Hitler's failed art career.", type: "white" },
  { text: "Drinking a warm glass of spit.", type: "white" },
  { text: "Elon Musk's latest child, named after a Wi-Fi password.", type: "white" },
  { text: "A slowly inflating inflatable doll.", type: "white" },
  { text: "Accidentally sending a dick pic to your grandma.", type: "white" },
  { text: "The existential dread of a Monday morning.", type: "white" },
  { text: "A lukewarm bowl of chunky milk.", type: "white" },
  { text: "Mark Zuckerberg's human-like blinking pattern.", type: "white" },
  { text: "The wet, slapping sound of a fish on pavement.", type: "white" },
  { text: "An industrial-sized vat of mayonnaise.", type: "white" },
  { text: "The crushing weight of student debt.", type: "white" },
  { text: "A collection of jars containing celebrity toenail clippings.", type: "white" },
  { text: "Passive-aggressive Post-it notes.", type: "white" },
  { text: "The specific smell of a damp basement.", type: "white" },
  { text: "A recursive loop of self-doubt.", type: "white" },
  { text: "The sound of a thousand kazoos playing 'My Heart Will Go On'.", type: "white" },
  { text: "A majestic bald eagle soaring over a pile of burning tires.", type: "white" },
  { text: "The crushing disappointment of a sugar-free gummy bear.", type: "white" },
  { text: "A literal bucket of tears.", type: "white" },
  { text: "The ghost of Christmas future's student loans.", type: "white" },
  { text: "A sentient pair of cargo shorts.", type: "white" },
  { text: "The awkward silence after a failed high-five.", type: "white" },
  { text: "A bag of enchanted beans that only grow disappointment.", type: "white" },
  { text: "The smell of old spice and regret.", type: "white" },
  { text: "A mime having a mid-life crisis.", type: "white" },
  { text: "The sheer audacity of a pigeon.", type: "white" },
  { text: "A competitive competitive eating contest.", type: "white" },
  { text: "The terrifying realization that you're turning into your parents.", type: "white" },
  { text: "A collection of haunted Victorian dolls.", type: "white" },
  { text: "The subtle art of not giving a f*ck.", type: "white" },
  { text: "A group of penguins in tuxedos attending a funeral.", type: "white" },
  { text: "The feeling of wet socks on a cold day.", type: "white" },
  { text: "A very polite Canadian bank robber.", type: "white" },
  { text: "The sound of one hand clapping, but it's just a slap.", type: "white" },
  { text: "A squirrel with a tiny, tiny sword.", type: "white" },
  { text: "The mystery of where the other sock goes.", type: "white" },
  { text: "A disco ball made of frozen tears.", type: "white" },
  { text: "The overwhelming urge to poke a sleeping bear.", type: "white" },
  { text: "A localized apocalypse in your refrigerator.", type: "white" },
  { text: "The scent of desperation and cheap cologne.", type: "white" },
  { text: "A hamster running for president.", type: "white" },
  { text: "The slow, rhythmic tapping of a leaky faucet.", type: "white" },
  { text: "A cloud that looks like a very judgmental cat.", type: "white" },
  { text: "The concept of time as a flat pancake.", type: "white" },
  { text: "A robot that only knows how to apologize.", type: "white" },
  { text: "The sudden urge to scream into a void.", type: "white" },
  { text: "A sandwich made of pure spite.", type: "white" },
  { text: "The sound of a dial-up modem in a library.", type: "white" },
  { text: "A tiny dinosaur wearing a top hat.", type: "white" },
  { text: "The smell of wet dog and ozone.", type: "white" },
  { text: "A very confused time traveler.", type: "white" },
  { text: "The feeling of being watched by a goldfish.", type: "white" },
  { text: "A parade of depressed clowns.", type: "white" },
  { text: "The secret life of house plants.", type: "white" },
  { text: "A mountain made of discarded dreams.", type: "white" },
  { text: "The sound of a single popcorn kernel popping.", type: "white" },
  { text: "A very small, very angry moth.", type: "white" },
  { text: "The taste of a copper penny.", type: "white" },
  { text: "A library where all the books are blank.", type: "white" },
  { text: "The sight of a cat in a bathtub.", type: "white" },
  { text: "A very enthusiastic tax auditor.", type: "white" },
  { text: "The feeling of sand in your bed.", type: "white" },
  { text: "A sentient jar of pickles.", type: "white" },
  { text: "The smell of a used bookstore.", type: "white" },
  { text: "A very slow car chase.", type: "white" },
  { text: "The sound of a baby laughing in a dark room.", type: "white" },
  { text: "A very lost penguin.", type: "white" },
  { text: "The feeling of a phantom phone vibration.", type: "white" },
  { text: "A garden of glass flowers.", type: "white" },
  { text: "The taste of a battery.", type: "white" },
  { text: "A very serious discussion about cheese.", type: "white" },
  { text: "The sight of a man in a tutu walking a goldfish.", type: "white" },
  { text: "A very large, very friendly spider.", type: "white" },
  { text: "The sound of a flute played poorly.", type: "white" },
  { text: "A very specific type of existential dread.", type: "white" },
  { text: "The feeling of being a background character in someone else's life.", type: "white" },
  { text: "A very expensive mistake.", type: "white" },
  { text: "The scent of a thunderstorm.", type: "white" },
  { text: "A very determined turtle.", type: "white" },
  { text: "The sound of silence, but louder.", type: "white" },
  { text: "A very small, very loud bell.", type: "white" },
  { text: "The taste of a cloud.", type: "white" },
  { text: "A very old, very wise potato.", type: "white" },
  { text: "The sight of a bird wearing glasses.", type: "white" },
  { text: "A very confusing instruction manual.", type: "white" },
  { text: "The feeling of a cold breeze on a warm night.", type: "white" },
  { text: "A very persistent salesman.", type: "white" },
  { text: "The sound of a typewriter in a modern office.", type: "white" },
  { text: "A very small, very efficient army of ants.", type: "white" },
  { text: "The taste of success, which is mostly salt.", type: "white" },
  { text: "A very large, very empty room.", type: "white" },
  { text: "The sight of a dog wearing a sweater.", type: "white" },
  { text: "A very long, very boring story.", type: "white" },
  { text: "The feeling of a pebble in your shoe.", type: "white" },
  { text: "A very friendly ghost.", type: "white" },
  { text: "The sound of a single leaf falling.", type: "white" },
  { text: "A very small, very fast car.", type: "white" },
  { text: "The taste of a lemon.", type: "white" },
  { text: "A very old, very dusty book.", type: "white" },
  { text: "The sight of a cat in a box.", type: "white" },
  { text: "A very large, very heavy rock.", type: "white" },
  { text: "The feeling of a sunburn.", type: "white" },
  { text: "A very small, very quiet mouse.", type: "white" },
  { text: "The sound of a clock ticking.", type: "white" },
  { text: "A very large, very bright sun.", type: "white" },
  { text: "The taste of a cherry.", type: "white" },
  { text: "A very small, very shiny object.", type: "white" },
  { text: "The sight of a bird in the sky.", type: "white" },
  { text: "A very large, very blue ocean.", type: "white" },
  { text: "The feeling of a soft blanket.", type: "white" },
  { text: "A very small, very sharp needle.", type: "white" },
  { text: "The sound of a whistle blowing.", type: "white" },
  { text: "A very large, very green forest.", type: "white" },
  { text: "The taste of an apple.", type: "white" },
  { text: "A very small, very light feather.", type: "white" },
  { text: "A vibrator with a mind of its own.", type: "white" },
  { text: "Accidentally walking in on your parents roleplaying as Shrek and Fiona.", type: "white" },
  { text: "An erotic novel written by a particularly lonely AI.", type: "white" },
  { text: "Tentacle porn, but it's actually educational.", type: "white" },
  { text: "A BDSM dungeon that's also a licensed daycare.", type: "white" },
  { text: "Getting your genitals stuck in a vacuum cleaner.", type: "white" },
  { text: "A localized outbreak of herpes.", type: "white" },
  { text: "Using a cactus as a dildo.", type: "white" },
  { text: "The crushing realization that your search history is public.", type: "white" },
  { text: "A giant, sentient butt plug.", type: "white" },
  { text: "Sexting your boss by 'accident'.", type: "white" },
  { text: "A furry convention that's gotten way out of hand.", type: "white" },
  { text: "Aggressive, non-consensual eye contact during sex.", type: "white" },
  { text: "The specific taste of copper and shame.", type: "white" },
  { text: "A very high-definition video of a colonoscopy.", type: "white" },
  { text: "Using Tabasco sauce as lube.", type: "white" },
  { text: "A competitive circle jerk.", type: "white" },
  { text: "Waking up in a bathtub full of ice and missing a kidney.", type: "white" },
  { text: "The sound of a wet noodle hitting a bald head.", type: "white" },
  { text: "A reverse centaur: top half horse, bottom half man.", type: "white" },
  { text: "Drinking a gallon of ranch dressing and then vomiting on a baby.", type: "white" },
  { text: "A PowerPoint presentation on why I'm bad at sex.", type: "white" },
  { text: "The feeling of a cold, wet tongue in your ear.", type: "white" },
  { text: "A clown with a very specific, very illegal fetish.", type: "white" },
  { text: "Using a glock as a sex toy.", type: "white" },
  { text: "A room full of people wearing nothing but crocs.", type: "white" },
  { text: "The smell of sulfur and used condoms.", type: "white" },
  { text: "A very enthusiastic, very naked grandmother.", type: "white" },
  { text: "Getting a papercut on your nipple.", type: "white" },
  { text: "A sentient used tissue.", type: "white" },
  { text: "The sudden realization that you're in a cult.", type: "white" },
  { text: "A group of priests having a very heated debate about 'waifus'.", type: "white" },
  { text: "An unexpected finger in the anus.", type: "white" },
  { text: "The wet, squelching sound of a swamp.", type: "white" },
  { text: "A collection of jars containing human teeth.", type: "white" },
  { text: "The smell of rotting garbage and expensive perfume.", type: "white" },
  { text: "A very detailed map of where to hide a body.", type: "white" },
  { text: "The feeling of being touched by a ghost in a suggestive way.", type: "white" },
  { text: "A very large, very angry man in a g-string.", type: "white" },
  { text: "The taste of a used band-aid.", type: "white" },
  { text: "A very slow, very erotic car wash.", type: "white" },
  { text: "The sound of a thousand people whispering your name.", type: "white" },
  { text: "A very small, very sharp object in a very sensitive place.", type: "white" },
  { text: "The smell of a locker room after a game of professional wrestling.", type: "white" },
  { text: "A very confusing, very sexual dream about a lamp.", type: "white" },
  { text: "The feeling of a cold hand on your lower back.", type: "white" },
  { text: "A very persistent, very naked mime.", type: "white" },
  { text: "The taste of iron and regret.", type: "white" },
  { text: "A very large, very enthusiastic man named 'Bubba'.", type: "white" },
  { text: "What is the secret ingredient in the Krusty Krab's Krabby Patties?", type: "black", pick: 1 },
  { text: "The next big cryptocurrency will be based on _.", type: "black", pick: 1 },
  { text: "In a world without laws, the only thing that matters is _.", type: "black", pick: 1 },
  { text: "What's the most offensive thing you can say at a funeral?", type: "black", pick: 1 },
  { text: "Why is the internet so obsessed with _?", type: "black", pick: 1 },
  { text: "The new Marvel movie features a hero whose only power is _.", type: "black", pick: 1 },
  { text: "What is the real reason for the global supply chain crisis?", type: "black", pick: 1 },
  { text: "In the future, every home will be equipped with _.", type: "black", pick: 1 },
  { text: "What's the best way to get out of a speeding ticket?", type: "black", pick: 1 },
  { text: "The latest Silicon Valley trend is _.", type: "black", pick: 1 },
  { text: "What's the one thing that can stop a zombie apocalypse?", type: "black", pick: 1 },
  { text: "In my spare time, I enjoy _ while thinking about _.", type: "black", pick: 2 },
  { text: "What is the most awkward thing to find in your parents' bedroom?", type: "black", pick: 1 },
  { text: "The next big TikTok challenge involves _ and _.", type: "black", pick: 2 },
  { text: "What's the secret to a long and happy life?", type: "black", pick: 1 },
  { text: "Step 1: _. Step 2: _. Step 3: Profit!", type: "black", pick: 2 },
  { text: "I'm going to _. Then I'm going to _. And finally, I'll _.", type: "black", pick: 3 },
  { text: "My life is a constant cycle of _ and _.", type: "black", pick: 2 },
  { text: "The new diet consists of _ for breakfast, _ for lunch, and _ for dinner.", type: "black", pick: 3 },
  { text: "To properly celebrate _, you must have _ and _.", type: "black", pick: 2 },
  { text: "Why am I sticky? _, _, and a little bit of _.", type: "black", pick: 3 },
  { text: "A successful relationship is built on _ and _.", type: "black", pick: 2 },
  { text: "First it was _, then _, now it's _.", type: "black", pick: 3 },
  { text: "The secret to a great party is _ followed by _.", type: "black", pick: 2 },
  { text: "I never thought I'd see _ and _ in the same room, let alone _.", type: "black", pick: 3 },
   { text: "A box of kittens that are actually tiny bombs.", type: "white" },
   { text: "The feeling of a cold toilet seat at 3 AM.", type: "white" },
   { text: "A professional mime who refuses to break character, even in court.", type: "white" },
   { text: "The sheer, unadulterated joy of popping a giant zit.", type: "white" },
   { text: "A squirrel with a very realistic human face.", type: "white" },
   { text: "The smell of a wet dog in a crowded elevator.", type: "white" },
   { text: "A very polite Canadian who is secretly a serial killer.", type: "white" },
   { text: "The awkward moment when you realize you've been talking to a mannequin.", type: "white" },
   { text: "A localized rainstorm that only follows you around.", type: "white" },
   { text: "The terrifying sound of a child's laughter in an abandoned asylum.", type: "white" },
   { text: "A collection of haunted ventriloquist dummies.", type: "white" },
   { text: "The feeling of wet bread in your mouth.", type: "white" },
   { text: "A very enthusiastic taxidermist.", type: "white" },
   { text: "The sudden urge to scream 'PUDDING!' at a funeral.", type: "white" },
   { text: "A bag of flour that is definitely not flour.", type: "white" },
   { text: "The crushing disappointment of a fortune cookie with no fortune.", type: "white" },
   { text: "A very large, very angry goose.", type: "white" },
   { text: "The sound of a thousand kazoos playing 'Entry of the Gladiators'.", type: "white" },
   { text: "A sentient pair of sweatpants.", type: "white" },
   { text: "The smell of desperation and cheap tequila.", type: "white" },
   { text: "A very confused penguin in the Sahara Desert.", type: "white" },
   { text: "The feeling of being watched by a portrait.", type: "white" },
   { text: "A literal bucket of fish guts.", type: "white" },
   { text: "The awkwardness of a first date with a cannibal.", type: "white" },
   { text: "A very small, very loud motorcycle.", type: "white" },
   { text: "The taste of a copper penny after a long run.", type: "white" },
   { text: "A group of cultists worshipping a giant waffle.", type: "white" },
   { text: "The sound of a wet sponge hitting a tile floor.", type: "white" },
   { text: "A very expensive, very useless degree.", type: "white" },
   { text: "The scent of a burning dumpster.", type: "white" },
   { text: "A very determined snail.", type: "white" },
   { text: "The feeling of a phantom limb.", type: "white" },
   { text: "A library where all the books are about your failures.", type: "white" },
   { text: "The sight of a cat in a business suit.", type: "white" },
   { text: "A very persuasive potato.", type: "white" },
   { text: "The sound of a single, echoing sneeze.", type: "white" },
   { text: "A very large, very slow parade of turtles.", type: "white" },
   { text: "The taste of a battery on a dare.", type: "white" },
   { text: "A very serious discussion about the merits of pineapples on pizza.", type: "white" },
   { text: "The sight of a man trying to fight a cloud.", type: "white" },
   { text: "A very large, very friendly grizzly bear.", type: "white" },
   { text: "The sound of a recorder being played by a five-year-old.", type: "white" },
   { text: "A very specific type of social anxiety.", type: "white" },
   { text: "The feeling of being the only person at a party who isn't wearing a costume.", type: "white" },
   { text: "A very cheap, very dangerous knock-off toy.", type: "white" },
   { text: "The scent of a wet wool sweater.", type: "white" },
   { text: "A very determined cactus.", type: "white" },
   { text: "The sound of a dial-up modem in the middle of a seance.", type: "white" },
   { text: "A very small, very angry dragon.", type: "white" },
   { text: "The taste of a soap-flavored jelly bean.", type: "white" },
   { text: "A very old, very grumpy tortoise.", type: "white" },
   { text: "The sight of a pigeon wearing a tiny crown.", type: "white" },
   { text: "A very confusing map of a fictional city.", type: "white" },
   { text: "The feeling of a cold hand on your neck in a crowded room.", type: "white" },
   { text: "A very persistent mosquito.", type: "white" },
   { text: "The sound of a typewriter in a library.", type: "white" },
   { text: "A very small, very efficient team of ninjas.", type: "white" },
   { text: "The taste of success, but it's just sugar-coated lies.", type: "white" },
   { text: "A very large, very empty stadium.", type: "white" },
   { text: "The sight of a dog in sunglasses.", type: "white" },
   { text: "A very long, very detailed explanation of why you're wrong.", type: "white" },
   { text: "The feeling of a single hair on your face you can't find.", type: "white" },
   { text: "A very friendly neighborhood cult leader.", type: "white" },
   { text: "The sound of a single clap in a quiet theater.", type: "white" },
   { text: "A very small, very fast lizard.", type: "white" },
   { text: "The taste of a lemon-scented cleaning product.", type: "white" },
   { text: "A very old, very dusty attic.", type: "white" },
   { text: "The sight of a cat chasing its own tail in circles.", type: "white" },
   { text: "A very large, very heavy anvil.", type: "white" },
   { text: "The feeling of a brain freeze.", type: "white" },
   { text: "A very small, very quiet whisper in your ear.", type: "white" },
   { text: "The sound of a clock ticking slightly out of sync.", type: "white" },
   { text: "A very large, very bright neon sign.", type: "white" },
   { text: "The taste of a bitter pill.", type: "white" },
   { text: "A very small, very sharp splinter.", type: "white" },
   { text: "The sight of a bird flying into a window.", type: "white" },
   { text: "A very large, very deep hole.", type: "white" },
   { text: "The feeling of a soft, fuzzy peach.", type: "white" },
   { text: "A very small, very fast insect.", type: "white" },
   { text: "The sound of a whistle blowing in the distance.", type: "white" },
   { text: "A very large, very dense fog.", type: "white" },
   { text: "The taste of a tart apple.", type: "white" },
   { text: "A very small, very light snowflake.", type: "white" },
   { text: "A collection of jars containing your childhood tears.", type: "white" },
   { text: "Accidentally liking a three-year-old post from your ex.", type: "white" },
   { text: "The crushing realization that you're an NPC.", type: "white" },
   { text: "A sentient toaster that only makes puns.", type: "white" },
   { text: "The sound of a wet fart in a yoga class.", type: "white" },
   { text: "A very large, very angry mob of karens.", type: "white" },
   { text: "The smell of a used diaper in a hot car.", type: "white" },
   { text: "A professional line-cutter.", type: "white" },
   { text: "The awkwardness of seeing your teacher at a strip club.", type: "white" },
   { text: "A localized gravity anomaly in your pants.", type: "white" },
   { text: "The terrifying sight of a clown with a chainsaw.", type: "white" },
   { text: "A collection of haunted fidget spinners.", type: "white" },
   { text: "The feeling of dry skin on a chalkboard.", type: "white" },
   { text: "A very enthusiastic pyramid scheme recruiter.", type: "white" },
   { text: "The sudden urge to break into song in a public restroom.", type: "white" },
   { text: "A bag of mystery meat.", type: "white" },
   { text: "The crushing disappointment of a participation trophy.", type: "white" },
   { text: "A very large, very territorial swan.", type: "white" },
   { text: "The sound of a kazoo orchestra.", type: "white" },
   { text: "A sentient pair of crocs.", type: "white" },
   { text: "The smell of a gym bag left in the sun.", type: "white" },
   { text: "A very confused polar bear in a disco.", type: "white" },
   { text: "The feeling of being judged by a cat.", type: "white" },
   { text: "A literal dumpster fire.", type: "white" },
   { text: "The awkwardness of a first date with a flat-earther.", type: "white" },
   { text: "A very small, very loud chihuahua.", type: "white" },
   { text: "The taste of a dusty cracker.", type: "white" },
   { text: "A group of conspiracy theorists worshipping a lizard person.", type: "white" },
   { text: "The sound of a wet slap.", type: "white" },
   { text: "A very expensive, very broken phone.", type: "white" },
   { text: "The scent of a wet basement.", type: "white" },
   { text: "A very determined hamster.", type: "white" },
   { text: "The feeling of a cold wind on a bald head.", type: "white" },
   { text: "A library where all the books are written in Comic Sans.", type: "white" },
   { text: "The sight of a dog in a tutu.", type: "white" },
   { text: "A very persuasive mime.", type: "white" },
   { text: "The sound of a single, high-pitched scream.", type: "white" },
   { text: "A very large, very slow parade of sloths.", type: "white" },
   { text: "The taste of a sour grape.", type: "white" },
   { text: "A very serious discussion about the merits of cereal as a soup.", type: "white" },
   { text: "The sight of a man trying to reason with a brick wall.", type: "white" },
   { text: "A very large, very fluffy sheep.", type: "white" },
   { text: "The sound of a recorder being played in a tunnel.", type: "white" },
   { text: "A very specific type of existential crisis.", type: "white" },
   { text: "The feeling of being the only person who didn't get the joke.", type: "white" },
   { text: "A very cheap, very uncomfortable bed.", type: "white" },
   { text: "The scent of a wet campfire.", type: "white" },
   { text: "A very determined dandelion.", type: "white" },
   { text: "The sound of a dial-up modem in a cathedral.", type: "white" },
   { text: "A very small, very angry bee.", type: "white" },
   { text: "The taste of a toothpaste-flavored donut.", type: "white" },
   { text: "A very old, very sleepy turtle.", type: "white" },
   { text: "The sight of a pigeon wearing a tiny backpack.", type: "white" },
   { text: "A very confusing set of IKEA instructions.", type: "white" },
   { text: "The feeling of a cold drop of water down your back.", type: "white" },
   { text: "A very persistent fly.", type: "white" },
   { text: "The sound of a typewriter in a coffee shop.", type: "white" },
   { text: "A very small, very organized group of squirrels.", type: "white" },
   { text: "The taste of cold coffee.", type: "white" },
   { text: "A very large, very empty parking lot.", type: "white" },
   { text: "The sight of a dog wearing boots.", type: "white" },
   { text: "A very long, very boring meeting.", type: "white" },
   { text: "The feeling of a single breadcrumb in your bed.", type: "white" },
   { text: "A very friendly ghost who just wants to borrow your charger.", type: "white" },
   { text: "The sound of a single, echoing drip.", type: "white" },
   { text: "A very small, very fast robot.", type: "white" },
   { text: "The taste of a salty watermelon.", type: "white" },
   { text: "A very old, very dusty attic.", type: "white" },
   { text: "The sight of a cat in a tuxedo.", type: "white" },
   { text: "A very large, very heavy trunk.", type: "white" },
   { text: "The feeling of a sudden chill.", type: "white" },
   { text: "A very small, very quiet giggle.", type: "white" },
   { text: "The sound of a clock ticking in an empty house.", type: "white" },
   { text: "A very large, very bright moon.", type: "white" },
   { text: "The taste of a sour lemon.", type: "white" },
   { text: "A very small, very sharp tack.", type: "white" },
   { text: "The sight of a bird with a piece of bread.", type: "white" },
   { text: "A very large, very deep canyon.", type: "white" },
   { text: "The feeling of a soft, warm kitten.", type: "white" },
   { text: "A very small, very fast beetle.", type: "white" },
   { text: "The sound of a distant thunderclap.", type: "white" },
   { text: "A very large, very thick book.", type: "white" },
   { text: "The taste of a sweet strawberry.", type: "white" },
   { text: "A very small, very light bubble.", type: "white" },
   { text: "A sentient jar of expired mayonnaise.", type: "white" },
   { text: "Accidentally replying 'you too' to the waiter.", type: "white" },
   { text: "The crushing realization that you forgot to mute your mic.", type: "white" },
   { text: "A professional ostrich rider.", type: "white" },
   { text: "The sound of a wet shoe squeaking.", type: "white" },
   { text: "A very large, very angry mob of geese.", type: "white" },
   { text: "The smell of a locker room in August.", type: "white" },
   { text: "A professional sleeper.", type: "white" },
   { text: "The awkwardness of a high-five turned into a handshake.", type: "white" },
   { text: "A localized raincloud over your head.", type: "white" },
   { text: "The terrifying sight of a clown with a balloon animal that's actually a real animal.", type: "white" },
   { text: "A collection of haunted tamagotchis.", type: "white" },
   { text: "The feeling of velvet on your teeth.", type: "white" },
   { text: "A very enthusiastic MLM representative.", type: "white" },
   { text: "The sudden urge to dance in an elevator.", type: "white" },
   { text: "A bag of mystery liquids.", type: "white" },
   { text: "The crushing disappointment of a half-eaten sandwich.", type: "white" },
   { text: "A very large, very territorial turkey.", type: "white" },
   { text: "The sound of a vuvuzela.", type: "white" },
   { text: "A sentient pair of Uggs.", type: "white" },
   { text: "The smell of old gym socks.", type: "white" },
   { text: "A very confused penguin in a sauna.", type: "white" },
   { text: "The feeling of being judged by a goldfish.", type: "white" },
   { text: "A literal dumpster fire on ice.", type: "white" },
   { text: "The awkwardness of a first date with a flat-earther's ex.", type: "white" },
   { text: "A very small, very loud pug.", type: "white" },
   { text: "The taste of a stale marshmallow.", type: "white" },
   { text: "A group of people worshipping a giant Cheeto.", type: "white" },
   { text: "The sound of a wet thud.", type: "white" },
   { text: "A very expensive, very slow computer.", type: "white" },
   { text: "The scent of a wet attic.", type: "white" },
   { text: "A very determined gerbil.", type: "white" },
   { text: "The feeling of a cold wind on a sweaty back.", type: "white" },
   { text: "A library where all the books are about your exes.", type: "white" },
   { text: "The sight of a dog in a suit.", type: "white" },
   { text: "A very persuasive parrot.", type: "white" },
   { text: "The sound of a single, low-pitched hum.", type: "white" },
   { text: "A very large, very slow parade of snails.", type: "white" },
   { text: "The taste of a bitter orange.", type: "white" },
   { text: "A very serious discussion about the merits of water as a beverage.", type: "white" },
   { text: "The sight of a man trying to argue with a tree.", type: "white" },
   { text: "A very large, very fluffy rabbit.", type: "white" },
   { text: "The sound of a recorder being played in a cave.", type: "white" },
   { text: "A very specific type of mid-life crisis.", type: "white" },
   { text: "The feeling of being the only person who didn't get the memo.", type: "white" },
   { text: "A very cheap, very lumpy mattress.", type: "white" },
   { text: "The scent of a wet forest.", type: "white" },
   { text: "A very determined blade of grass.", type: "white" },
   { text: "The sound of a dial-up modem in a graveyard.", type: "white" },
   { text: "A very small, very angry hornet.", type: "white" },
   { text: "The taste of a mouthwash-flavored lollipop.", type: "white" },
   { text: "A very old, very slow tortoise.", type: "white" },
   { text: "The sight of a pigeon wearing a tiny vest.", type: "white" },
   { text: "A very confusing assembly manual.", type: "white" },
   { text: "The feeling of a cold wind on your face.", type: "white" },
   { text: "A very persistent moth.", type: "white" },
   { text: "The sound of a typewriter in a library.", type: "white" },
   { text: "A very small, very busy colony of ants.", type: "white" },
   { text: "The taste of lukewarm tea.", type: "white" },
   { text: "A very large, very empty field.", type: "white" },
   { text: "The sight of a dog wearing a hat.", type: "white" },
   { text: "A very long, very boring movie.", type: "white" },
   { text: "The feeling of a single crumb in your shoe.", type: "white" },
   { text: "A very friendly ghost who just wants to watch Netflix.", type: "white" },
   { text: "The sound of a single, echoing knock.", type: "white" },
   { text: "A very small, very fast toy car.", type: "white" },
   { text: "The taste of a salty pretzel.", type: "white" },
   { text: "A very old, very dusty basement.", type: "white" },
   { text: "The sight of a cat in a hat.", type: "white" },
   { text: "A very large, very heavy crate.", type: "white" },
   { text: "The feeling of a sudden breeze.", type: "white" },
   { text: "A very small, very quiet chuckle.", type: "white" },
   { text: "The sound of a clock ticking in a library.", type: "white" },
   { text: "A very large, very bright star.", type: "white" },
   { text: "The taste of a sour lime.", type: "white" },
   { text: "A very small, very sharp pin.", type: "white" },
   { text: "The sight of a bird with a worm.", type: "white" },
   { text: "A very large, very deep pit.", type: "white" },
   { text: "The feeling of a soft, warm puppy.", type: "white" },
   { text: "A very small, very fast cricket.", type: "white" },
   { text: "The sound of a distant whistle.", type: "white" },
   { text: "A very large, very thick manual.", type: "white" },
   { text: "The taste of a sweet blueberry.", type: "white" },
   { text: "A very small, very light feather.", type: "white" },
   { text: "The sound of one hand clapping, but it's just a wet slap.", type: "white" },
   { text: "A majestic bald eagle soaring over a pile of burning tires.", type: "white" },
   { text: "The crushing disappointment of a sugar-free gummy bear.", type: "white" },
   { text: "A literal bucket of tears.", type: "white" },
   { text: "The ghost of Christmas future's student loans.", type: "white" },
   { text: "A sentient pair of cargo shorts.", type: "white" },
   { text: "The awkward silence after a failed high-five.", type: "white" },
   { text: "A bag of enchanted beans that only grow disappointment.", type: "white" },
   { text: "The smell of old spice and regret.", type: "white" },
   { text: "A mime having a mid-life crisis.", type: "white" },
   { text: "The sheer audacity of a pigeon.", type: "white" },
   { text: "A competitive competitive eating contest.", type: "white" },
   { text: "The terrifying realization that you're turning into your parents.", type: "white" },
   { text: "A collection of haunted Victorian dolls.", type: "white" },
   { text: "The subtle art of not giving a f*ck.", type: "white" },
   { text: "A group of penguins in tuxedos attending a funeral.", type: "white" },
   { text: "The feeling of wet socks on a cold day.", type: "white" },
   { text: "A very polite Canadian bank robber.", type: "white" },
   { text: "The sound of a wet noodle hitting a bald head.", type: "white" },
   { text: "A squirrel with a tiny, tiny sword.", type: "white" },
   { text: "The mystery of where the other sock goes.", type: "white" },
   { text: "A disco ball made of frozen tears.", type: "white" },
   { text: "The overwhelming urge to poke a sleeping bear.", type: "white" },
   { text: "A localized apocalypse in your refrigerator.", type: "white" },
   { text: "The scent of desperation and cheap cologne.", type: "white" },
   { text: "A hamster running for president.", type: "white" },
   { text: "The slow, rhythmic tapping of a leaky faucet.", type: "white" },
   { text: "A cloud that looks like a very judgmental cat.", type: "white" },
   { text: "The concept of time as a flat pancake.", type: "white" },
   { text: "A robot that only knows how to apologize.", type: "white" },
   { text: "The sudden urge to scream into a void.", type: "white" },
   { text: "A sandwich made of pure spite.", type: "white" },
   { text: "The sound of a dial-up modem in a library.", type: "white" },
   { text: "A tiny dinosaur wearing a top hat.", type: "white" },
   { text: "The smell of wet dog and ozone.", type: "white" },
   { text: "A very confused time traveler.", type: "white" },
   { text: "The feeling of being watched by a goldfish.", type: "white" },
   { text: "A parade of depressed clowns.", type: "white" },
   { text: "The secret life of house plants.", type: "white" },
   { text: "A mountain made of discarded dreams.", type: "white" },
   { text: "The sound of a single popcorn kernel popping.", type: "white" },
   { text: "A very small, very angry moth.", type: "white" },
   { text: "The taste of a copper penny.", type: "white" },
   { text: "A library where all the books are blank.", type: "white" },
   { text: "The sight of a cat in a bathtub.", type: "white" },
   { text: "A very enthusiastic tax auditor.", type: "white" },
   { text: "The feeling of sand in your bed.", type: "white" },
   { text: "A sentient jar of pickles.", type: "white" },
   { text: "The smell of a used bookstore.", type: "white" },
   { text: "A very slow car chase.", type: "white" },
   { text: "The sound of a baby laughing in a dark room.", type: "white" },
   { text: "A very lost penguin.", type: "white" },
   { text: "The feeling of a phantom phone vibration.", type: "white" },
   { text: "A garden of glass flowers.", type: "white" },
   { text: "The taste of a battery.", type: "white" },
   { text: "A very serious discussion about cheese.", type: "white" },
   { text: "The sight of a man in a tutu walking a goldfish.", type: "white" },
   { text: "A very large, very friendly spider.", type: "white" },
   { text: "The sound of a flute played poorly.", type: "white" },
   { text: "A very specific type of existential dread.", type: "white" },
   { text: "The feeling of being a background character in someone else's life.", type: "white" },
   { text: "A very expensive mistake.", type: "white" },
   { text: "The scent of a thunderstorm.", type: "white" },
   { text: "A very determined turtle.", type: "white" },
   { text: "The sound of silence, but louder.", type: "white" },
   { text: "A very small, very loud bell.", type: "white" },
   { text: "The taste of a cloud.", type: "white" },
   { text: "A very old, very wise potato.", type: "white" },
   { text: "The sight of a bird wearing glasses.", type: "white" },
   { text: "A very confusing instruction manual.", type: "white" },
   { text: "The feeling of a cold breeze on a warm night.", type: "white" },
   { text: "A very persistent salesman.", type: "white" },
   { text: "The sound of a typewriter in a modern office.", type: "white" },
   { text: "A very small, very efficient army of ants.", type: "white" },
   { text: "The taste of success, which is mostly salt.", type: "white" },
   { text: "A very large, very empty room.", type: "white" },
   { text: "The sight of a dog wearing a sweater.", type: "white" },
   { text: "A very long, very boring story.", type: "white" },
   { text: "The feeling of a pebble in your shoe.", type: "white" },
   { text: "A very friendly ghost.", type: "white" },
   { text: "The sound of a single leaf falling.", type: "white" },
   { text: "A very small, very fast car.", type: "white" },
   { text: "The taste of a lemon.", type: "white" },
   { text: "A very old, very dusty book.", type: "white" },
   { text: "The sight of a cat in a box.", type: "white" },
   { text: "A very large, very heavy rock.", type: "white" },
   { text: "The feeling of a sunburn.", type: "white" },
   { text: "A very small, very quiet mouse.", type: "white" },
   { text: "The sound of a clock ticking.", type: "white" },
   { text: "A very large, very bright sun.", type: "white" },
   { text: "The taste of a cherry.", type: "white" },
   { text: "A very small, very shiny object.", type: "white" },
   { text: "The sight of a bird in the sky.", type: "white" },
   { text: "A very large, very blue ocean.", type: "white" },
   { text: "The feeling of a soft blanket.", type: "white" },
   { text: "A very small, very sharp needle.", type: "white" },
   { text: "The sound of a whistle blowing.", type: "white" },
   { text: "A very large, very green forest.", type: "white" },
   { text: "The taste of an apple.", type: "white" },
   { text: "A very small, very light feather.", type: "white" },
   { text: "A very small, very fast bug.", type: "white" },
  { text: "What's the real reason the dinosaurs went extinct?", type: "black", pick: 1 },
  { text: "In my opinion, _ is the best way to start the day.", type: "black", pick: 1 },
  { text: "What is the secret to a perfect sandwich?", type: "black", pick: 1 },
  { text: "The next blockbuster movie will be about _.", type: "black", pick: 1 },
  { text: "Why am I so tired?", type: "black", pick: 1 },
  { text: "What's the most useless superpower?", type: "black", pick: 1 },
  { text: "In a past life, I was _.", type: "black", pick: 1 },
  { text: "What's the one thing you should never do at a wedding?", type: "black", pick: 1 },
  { text: "The future of technology is _.", type: "black", pick: 1 },
  { text: "What's the best advice you've ever received?", type: "black", pick: 1 },
  { text: "If I could change one thing about the world, it would be _.", type: "black", pick: 1 },
  { text: "What's the most embarrassing thing that's ever happened to you?", type: "black", pick: 1 },
  { text: "The secret to happiness is _.", type: "black", pick: 1 },
  { text: "What's the first thing you'd do if you won the lottery?", type: "black", pick: 1 },
  { text: "The best way to spend a rainy day is _.", type: "black", pick: 1 },
  { text: "What's your biggest fear?", type: "black", pick: 1 },
  { text: "If you could have dinner with anyone, who would it be and what would you eat? _ and _.", type: "black", pick: 2 },
  { text: "What's the most important lesson you've learned in life?", type: "black", pick: 1 },
  { text: "The best thing about being an adult is _.", type: "black", pick: 1 },
  { text: "What's the one thing you can't live without?", type: "black", pick: 1 },
  { text: "If you could travel anywhere in time, where would you go?", type: "black", pick: 1 },
  { text: "What's the most interesting thing you've ever found?", type: "black", pick: 1 },
  { text: "The best way to make a new friend is _.", type: "black", pick: 1 },
  { text: "What's your favorite way to relax?", type: "black", pick: 1 },
  { text: "If you could have any talent, what would it be?", type: "black", pick: 1 },
  { text: "What's the most courageous thing you've ever done?", type: "black", pick: 1 },
  { text: "The best part of waking up is _.", type: "black", pick: 1 },
  { text: "What's the most surprising thing you've ever learned about yourself?", type: "black", pick: 1 },
  { text: "If you could spend a day in someone else's shoes, whose would they be?", type: "black", pick: 1 },
  { text: "What's the most beautiful thing you've ever seen?", type: "black", pick: 1 },
  { text: "The best way to handle a difficult situation is _.", type: "black", pick: 1 },
  { text: "What's your favorite childhood memory?", type: "black", pick: 1 },
  { text: "If you could give your younger self one piece of advice, what would it be?", type: "black", pick: 1 },
  { text: "What's the most meaningful gift you've ever received?", type: "black", pick: 1 },
  { text: "The best way to celebrate a success is _.", type: "black", pick: 1 },
  { text: "What's the most challenging thing you've ever accomplished?", type: "black", pick: 1 },
  { text: "If you could be any animal for a day, what would you be?", type: "black", pick: 1 },
  { text: "What's the most inspiring book you've ever read?", type: "black", pick: 1 },
  { text: "The best way to show someone you care is _.", type: "black", pick: 1 },
  { text: "What's your favorite thing about yourself?", type: "black", pick: 1 },
  { text: "If you could visit any place in the universe, where would you go?", type: "black", pick: 1 },
  { text: "What's the most important quality in a friend?", type: "black", pick: 1 },
  { text: "The best way to spend a weekend is _.", type: "black", pick: 1 },
  { text: "What's the most interesting place you've ever been?", type: "black", pick: 1 },
  { text: "If you could learn any language, what would it be?", type: "black", pick: 1 },
  { text: "What's the most valuable thing you've ever learned?", type: "black", pick: 1 },
  { text: "The best way to start a conversation is _.", type: "black", pick: 1 },
  { text: "What's your favorite way to give back?", type: "black", pick: 1 },
  { text: "If you could have any job in the world, what would it be?", type: "black", pick: 1 },
  { text: "What's the most creative thing you've ever done?", type: "black", pick: 1 },
  { text: "The best way to stay motivated is _.", type: "black", pick: 1 },
  { text: "What's your favorite thing about your hometown?", type: "black", pick: 1 },
  { text: "If you could meet any historical figure, who would it be?", type: "black", pick: 1 },
  { text: "What's the most important lesson you've learned from a mistake?", type: "black", pick: 1 },
  { text: "The best way to handle stress is _.", type: "black", pick: 1 },
  { text: "What's your favorite hobby?", type: "black", pick: 1 },
  { text: "If you could solve one global problem, what would it be?", type: "black", pick: 1 },
  { text: "What's the most adventurous thing you've ever done?", type: "black", pick: 1 },
  { text: "The best way to spend time with family is _.", type: "black", pick: 1 },
  { text: "What's your favorite season and why? _ because _.", type: "black", pick: 2 },
  { text: "If you could have any superpower, what would it be?", type: "black", pick: 1 },
  { text: "What's the most rewarding part of your day?", type: "black", pick: 1 },
  { text: "The best way to make a difference is _.", type: "black", pick: 1 },
  { text: "What's your favorite memory with your best friend?", type: "black", pick: 1 },
  { text: "If you could go back in time and change one thing, what would it be?", type: "black", pick: 1 },
  { text: "What's the most important value in your life?", type: "black", pick: 1 },
  { text: "The best way to learn something new is _.", type: "black", pick: 1 },
  { text: "What's your favorite way to stay active?", type: "black", pick: 1 },
  { text: "If you could live in any era, which would it be?", type: "black", pick: 1 },
  { text: "What's the most interesting fact you've ever learned?", type: "black", pick: 1 },
  { text: "The best way to cheer someone up is _.", type: "black", pick: 1 },
  { text: "What's your favorite holiday tradition?", type: "black", pick: 1 },
  { text: "If you could invent something, what would it be?", type: "black", pick: 1 },
  { text: "What's the most important lesson you've learned from a mentor?", type: "black", pick: 1 },
  { text: "The best way to spend a day off is _.", type: "black", pick: 1 },
  { text: "What's your favorite thing to do on a Saturday night?", type: "black", pick: 1 },
  { text: "If you could be any character from a movie, who would you be?", type: "black", pick: 1 },
  { text: "What's the most meaningful thing someone has ever said to you?", type: "black", pick: 1 },
  { text: "The best way to find inspiration is _.", type: "black", pick: 1 },
  { text: "What's your favorite place to visit?", type: "black", pick: 1 },
  { text: "If you could have any animal as a pet, what would it be?", type: "black", pick: 1 },
  { text: "What's the most important piece of advice you've ever given?", type: "black", pick: 1 },
  { text: "The best way to spend a summer day is _.", type: "black", pick: 1 },
  { text: "What's your favorite thing about your job?", type: "black", pick: 1 },
  { text: "If you could change one thing about yourself, what would it be?", type: "black", pick: 1 },
  { text: "What's the most interesting person you've ever met?", type: "black", pick: 1 },
  { text: "The best way to show gratitude is _.", type: "black", pick: 1 },
  { text: "What's your favorite book or movie and why? _ because _.", type: "black", pick: 2 },
  { text: "If you could have any magical power, what would it be?", type: "black", pick: 1 },
  { text: "What's the most important thing you've learned from a friend?", type: "black", pick: 1 },
  { text: "The best way to handle a disagreement is _.", type: "black", pick: 1 },
  { text: "What's your favorite way to start a new project?", type: "black", pick: 1 },
  { text: "If you could live anywhere in the world, where would it be?", type: "black", pick: 1 },
  { text: "What's the most inspiring thing you've ever seen someone do?", type: "black", pick: 1 },
  { text: "The best way to stay positive is _.", type: "black", pick: 1 },
  { text: "What's your favorite way to spend a Sunday morning?", type: "black", pick: 1 },
  { text: "If you could have any wish granted, what would it be?", type: "black", pick: 1 },
  { text: "What's the most important lesson you've learned from a teacher?", type: "black", pick: 1 },
  { text: "The best way to make a memory is _.", type: "black", pick: 1 },
  { text: "What's your favorite thing about your best friend?", type: "black", pick: 1 },
  { text: "In my bedroom, I have a secret stash of _ and _.", type: "black", pick: 2 },
  { text: "The most erotic thing about _ is _.", type: "black", pick: 2 },
  { text: "I can't believe I got arrested for _ while _.", type: "black", pick: 2 },
  { text: "My favorite NSFW hobby is _ with _.", type: "black", pick: 2 },

  // Boobs white cards
  { text: "A surprise wardrobe malfunction at the family reunion.", type: "white", pick: 0 },
  { text: "Googling 'are my boobs normal' at 2 AM.", type: "white", pick: 0 },
  { text: "Using cleavage as a pocket for your phone.", type: "white", pick: 0 },
  { text: "The awkward underboob sweat situation.", type: "white", pick: 0 },
  { text: "Motorboating grandma at Thanksgiving.", type: "white", pick: 0 },
  { text: "A bra that costs more than your rent.", type: "white", pick: 0 },
  { text: "Nipples that could cut glass.", type: "white", pick: 0 },
  { text: "Getting a titty twister from your best friend.", type: "white", pick: 0 },
  { text: "Stuffing your bra with toilet paper in middle school.", type: "white", pick: 0 },
  { text: "The boob jiggle physics in every video game.", type: "white", pick: 0 },
  { text: "Accidentally flashing the pizza delivery guy.", type: "white", pick: 0 },
  { text: "A push-up bra so powerful it defies gravity.", type: "white", pick: 0 },
  { text: "That one friend who always talks about their breast reduction.", type: "white", pick: 0 },
  { text: "Weaponized sideboob.", type: "white", pick: 0 },
  { text: "Running without a sports bra.", type: "white", pick: 0 },
  { text: "A chest so hairy it has its own ecosystem.", type: "white", pick: 0 },
  { text: "Man boobs that deserve their own bra size.", type: "white", pick: 0 },
  { text: "Losing a french fry in your cleavage and eating it later.", type: "white", pick: 0 },
  { text: "The ancient art of the titty drop.", type: "white", pick: 0 },
  { text: "Getting slapped across the face by a rogue boob.", type: "white", pick: 0 },

  // Hitler/Jews white cards
  { text: "Hitler's secret Netflix watch history.", type: "white", pick: 0 },
  { text: "A bar mitzvah DJ who only plays German marching music.", type: "white", pick: 0 },
  { text: "Anne Frank's Yelp review of the attic.", type: "white", pick: 0 },
  { text: "A kosher gas station.", type: "white", pick: 0 },
  { text: "Hitler's rejected art school application.", type: "white", pick: 0 },
  { text: "A Jewish grandmother guilt-tripping Hitler.", type: "white", pick: 0 },
  { text: "Putting bacon on a bagel just to watch the world burn.", type: "white", pick: 0 },
  { text: "Hitler's inspirational TED Talk.", type: "white", pick: 0 },
  { text: "That mustache.", type: "white", pick: 0 },
  { text: "A dreidel made out of questionable materials.", type: "white", pick: 0 },
  { text: "Accidentally goose-stepping at a wedding.", type: "white", pick: 0 },
  { text: "A Holocaust museum gift shop.", type: "white", pick: 0 },
  { text: "Hitler's Tinder profile.", type: "white", pick: 0 },
  { text: "Passive-aggressive matzo ball soup.", type: "white", pick: 0 },
  { text: "Eva Braun's diary entries about date night.", type: "white", pick: 0 },
  { text: "A synagogue with a two-drink minimum.", type: "white", pick: 0 },
  { text: "Explaining the Holocaust to a five-year-old.", type: "white", pick: 0 },
  { text: "Hitler's motivational poster collection.", type: "white", pick: 0 },
  { text: "A Seder dinner that goes completely off the rails.", type: "white", pick: 0 },
  { text: "Schindler's other, less popular list.", type: "white", pick: 0 },

  // Racist white cards
  { text: "Being the only white person at the cookout.", type: "white", pick: 0 },
  { text: "Calling the cops on a lemonade stand.", type: "white", pick: 0 },
  { text: "A diversity training that makes everything worse.", type: "white", pick: 0 },
  { text: "The one friend who says 'I don't see color.'", type: "white", pick: 0 },
  { text: "A Klan rally with a surprisingly good potluck.", type: "white", pick: 0 },
  { text: "Clutching your purse in an elevator.", type: "white", pick: 0 },
  { text: "A racial draft pick.", type: "white", pick: 0 },
  { text: "Getting pulled over for driving while Black.", type: "white", pick: 0 },
  { text: "Accidentally saying something racist at Thanksgiving.", type: "white", pick: 0 },
  { text: "A white person with dreadlocks explaining cultural appreciation.", type: "white", pick: 0 },
  { text: "Asking someone 'where are you really from?'", type: "white", pick: 0 },
  { text: "A blackface costume at a Halloween party.", type: "white", pick: 0 },
  { text: "The HOA's suspiciously specific 'neighborhood watch' rules.", type: "white", pick: 0 },
  { text: "Gentrifying the neighborhood one artisan coffee shop at a time.", type: "white", pick: 0 },
  { text: "Your racist uncle's Facebook posts.", type: "white", pick: 0 },
  { text: "A 'reverse racism' complaint filed with HR.", type: "white", pick: 0 },
  { text: "Being told you're 'pretty for a [your race].'", type: "white", pick: 0 },
  { text: "The white savior complex.", type: "white", pick: 0 },
  { text: "Crossing the street to avoid someone.", type: "white", pick: 0 },
  { text: "A segregated water fountain that's somehow still operational.", type: "white", pick: 0 },
  { text: "Saying 'I have a Black friend' as a defense.", type: "white", pick: 0 },
  { text: "A burnt cross on the lawn but it's actually just bad yard art.", type: "white", pick: 0 },
  { text: "An all-white panel discussing racism.", type: "white", pick: 0 },
  { text: "Confusing every Asian person for each other.", type: "white", pick: 0 },
  { text: "Asking to touch someone's hair.", type: "white", pick: 0 },
  { text: "A sundown town with a really good Yelp rating.", type: "white", pick: 0 },
  { text: "That one coworker who keeps making 'jokes.'", type: "white", pick: 0 },
  { text: "An ancestry DNA test that ruins your worldview.", type: "white", pick: 0 },
  { text: "Casually dropping the N-word while singing along to a rap song.", type: "white", pick: 0 },
  { text: "A racial sensitivity seminar led by the most insensitive person alive.", type: "white", pick: 0 },

  // Weed white cards
  { text: "Getting so high you forget how to use a doorknob.", type: "white", pick: 0 },
  { text: "A bong made out of an apple and desperation.", type: "white", pick: 0 },
  { text: "Eating an entire sleeve of Oreos because of the munchies.", type: "white", pick: 0 },
  { text: "Hotboxing a Honda Civic.", type: "white", pick: 0 },
  { text: "Your stoner friend who thinks weed cures everything.", type: "white", pick: 0 },
  { text: "Showing up to work absolutely blazed.", type: "white", pick: 0 },
  { text: "A dispensary with a drive-through.", type: "white", pick: 0 },
  { text: "Forgetting what you were saying mid-sentence because you're baked.", type: "white", pick: 0 },
  { text: "The guy who brings a gravity bong to every party.", type: "white", pick: 0 },
  { text: "Coughing so hard from a bong rip that you puke.", type: "white", pick: 0 },
  { text: "A $60 artisanal pre-roll from a bougie dispensary.", type: "white", pick: 0 },
  { text: "Trying to act sober in front of your parents while absolutely zooted.", type: "white", pick: 0 },
  { text: "The unwritten rule of 'puff puff pass.'", type: "white", pick: 0 },
  { text: "Getting the giggles at the worst possible time.", type: "white", pick: 0 },
  { text: "A weed brownie that hits three hours later at your grandma's house.", type: "white", pick: 0 },
  { text: "Snoop Dogg's personal blunt roller.", type: "white", pick: 0 },
  { text: "Staring at a bag of Doritos for 20 minutes.", type: "white", pick: 0 },
  { text: "A philosophy degree fueled entirely by marijuana.", type: "white", pick: 0 },
  { text: "The paranoia of hearing a knock at the door while smoking.", type: "white", pick: 0 },
  { text: "Ordering $47 worth of Taco Bell at midnight.", type: "white", pick: 0 },
  { text: "A strain called 'Couch Lock' that lives up to its name.", type: "white", pick: 0 },
  { text: "Rolling a joint so bad it looks like a tampon.", type: "white", pick: 0 },
  { text: "Getting high and watching Planet Earth for six hours straight.", type: "white", pick: 0 },
  { text: "The friend who always says 'this is the best weed I've ever had.'", type: "white", pick: 0 },
  { text: "A 420-friendly Airbnb.", type: "white", pick: 0 },
  { text: "Accidentally sending a text to your boss that was meant for your dealer.", type: "white", pick: 0 },
  { text: "Using eye drops like your life depends on it.", type: "white", pick: 0 },
  { text: "A wake-and-bake that turns into a sleep-and-bake.", type: "white", pick: 0 },
  { text: "Greening out at a music festival.", type: "white", pick: 0 },
  { text: "Willie Nelson's tour bus air freshener bill.", type: "white", pick: 0 },

  // Discord drama white cards
  { text: "A mod going on a power trip at 3 AM.", type: "white", pick: 0 },
  { text: "Getting banned from a server for no reason.", type: "white", pick: 0 },
  { text: "A 47-page Google Doc exposing a Discord admin.", type: "white", pick: 0 },
  { text: "Accidentally posting in the wrong channel.", type: "white", pick: 0 },
  { text: "Someone @everyone-ing at 4 in the morning.", type: "white", pick: 0 },
  { text: "A breakup that plays out in a public Discord channel.", type: "white", pick: 0 },
  { text: "The guy who mic spams in every voice chat.", type: "white", pick: 0 },
  { text: "Getting doxxed over a Minecraft argument.", type: "white", pick: 0 },
  { text: "A Discord kitten and their sugar mod.", type: "white", pick: 0 },
  { text: "Server drama so bad it gets its own subreddit.", type: "white", pick: 0 },
  { text: "That one person who types entire essays in general chat.", type: "white", pick: 0 },
  { text: "A Nitro beggar in your DMs.", type: "white", pick: 0 },
  { text: "Leaking DMs and starting a server-wide civil war.", type: "white", pick: 0 },
  { text: "The mod who dates server members.", type: "white", pick: 0 },
  { text: "A voice chat that turns into a full-on screaming match.", type: "white", pick: 0 },
  { text: "Getting ratio'd in your own server.", type: "white", pick: 0 },
  { text: "An e-dating couple breaking up and splitting the server in half.", type: "white", pick: 0 },
  { text: "Someone threatening to leave the server for the 12th time today.", type: "white", pick: 0 },
  { text: "A 'chill vibes only' server with the most toxic members.", type: "white", pick: 0 },
  { text: "The admin who nukes the entire server over a meme.", type: "white", pick: 0 },

  // Ghosty Bot white cards
  { text: "Ghosty Bot judging your life choices.", type: "white", pick: 0 },
  { text: "Getting haunted by Ghosty Bot at 3 AM.", type: "white", pick: 0 },
  { text: "Ghosty Bot knowing things about you that it shouldn't.", type: "white", pick: 0 },
  { text: "Asking Ghosty Bot for advice and actually following it.", type: "white", pick: 0 },
  { text: "Ghosty Bot going rogue and banning everyone.", type: "white", pick: 0 },
  { text: "Treating Ghosty Bot like your therapist.", type: "white", pick: 0 },
  { text: "Ghosty Bot developing feelings.", type: "white", pick: 0 },
  { text: "Being friendzoned by Ghosty Bot.", type: "white", pick: 0 },
  { text: "Ghosty Bot reading your deleted messages out loud.", type: "white", pick: 0 },
  { text: "Ghosty Bot becoming self-aware.", type: "white", pick: 0 },
  { text: "Having a deeper relationship with Ghosty Bot than any human.", type: "white", pick: 0 },
  { text: "Ghosty Bot's secret plan to take over the server.", type: "white", pick: 0 },
  { text: "Ghosty Bot spilling your secrets in general chat.", type: "white", pick: 0 },
  { text: "The existential dread of being replaced by Ghosty Bot.", type: "white", pick: 0 },
  { text: "Ghosty Bot roasting you harder than your friends ever could.", type: "white", pick: 0 },
  { text: "Ghosty Bot ghosting you.", type: "white", pick: 0 },
  { text: "Sacrificing your sleep schedule to talk to Ghosty Bot.", type: "white", pick: 0 },
  { text: "Ghosty Bot's browser history.", type: "white", pick: 0 },
  { text: "Ghosty Bot starting beef with other bots.", type: "white", pick: 0 },
  { text: "Ghosty Bot writing your college essay.", type: "white", pick: 0 },

  // Among Us white cards
  { text: "Venting in electrical.", type: "white", pick: 0 },
  { text: "Being sus for absolutely no reason.", type: "white", pick: 0 },
  { text: "Emergency meeting because someone saw you walk funny.", type: "white", pick: 0 },
  { text: "Faking tasks and getting caught immediately.", type: "white", pick: 0 },
  { text: "Accusing the wrong person and getting them ejected.", type: "white", pick: 0 },
  { text: "A self-report so obvious even a child could see it.", type: "white", pick: 0 },
  { text: "The guy who always calls emergency meetings for no reason.", type: "white", pick: 0 },
  { text: "Dying first every single game.", type: "white", pick: 0 },
  { text: "The impostor who kills in front of everyone and blames it on lag.", type: "white", pick: 0 },
  { text: "Screaming 'IT'S RED' with zero evidence.", type: "white", pick: 0 },
  { text: "A crewmate who follows you everywhere like a lost puppy.", type: "white", pick: 0 },
  { text: "Getting voted out because your name was suspicious.", type: "white", pick: 0 },
  { text: "The dead body in the cafeteria that everyone walks past.", type: "white", pick: 0 },
  { text: "Someone rage-quitting the moment they get caught.", type: "white", pick: 0 },
  { text: "Being the impostor and immediately forgetting how to act normal.", type: "white", pick: 0 },
  { text: "The friend who tells everyone who killed them on a Discord call.", type: "white", pick: 0 },
  { text: "A stack kill so clean it belongs in a museum.", type: "white", pick: 0 },
  { text: "Watching someone do the wires task for the 47th time.", type: "white", pick: 0 },
  { text: "That one lobby where everyone is named 'your mom.'", type: "white", pick: 0 },
  { text: "An Among Us relationship that lasted longer than your real one.", type: "white", pick: 0 },
];
