export const initialCards = [
  // Black Cards (Questions)
  { text: "Why can't I sleep at night?", type: "black", pick: 1 },
  { text: "I got 99 problems but _ ain't one.", type: "black", pick: 1 },
  { text: "What's a girl's best friend?", type: "black", pick: 1 },
  { text: "What's that smell?", type: "black", pick: 1 },
  { text: "This is the way the world ends. Not with a bang but with _.", type: "black", pick: 1 },
  { text: "What is Batman's guilty pleasure?", type: "black", pick: 1 },
  { text: "TSA guidelines now prohibit _ on airplanes.", type: "black", pick: 1 },
  { text: "What ended my last relationship?", type: "black", pick: 1 },
  { text: "MTV's new reality show features eight washed-up celebrities living with _.", type: "black", pick: 1 },
  { text: "I drink to forget _.", type: "black", pick: 1 },
  { text: "I'm sorry, Professor, but I couldn't complete my homework because of _.", type: "black", pick: 1 },
  { text: "Alternative medicine is now embracing the curative powers of _.", type: "black", pick: 1 },
  { text: "What's the next Happy Meal® toy?", type: "black", pick: 1 },
  { text: "What's the most emo?", type: "black", pick: 1 },
  { text: "During his midlife crisis, my dad got into _.", type: "black", pick: 1 },
  { text: "What's the next scandalous thing Donald Trump will tweet?", type: "black", pick: 1 },
  { text: "In the new Among Us update, the Impostor can now use _ to kill.", type: "black", pick: 1 },
  { text: "What was the real reason Jeffrey Epstein didn't kill himself?", type: "black", pick: 1 },
  { text: "Adolf Hitler's secret hobby was actually _.", type: "black", pick: 1 },
  { text: "The most erotic thing about a French accent is _.", type: "black", pick: 1 },

  // White Cards (Answers)
  { text: "Coat hanger abortions.", type: "white" },
  { text: "Man meat.", type: "white" },
  { text: "Autocannibalism.", type: "white" },
  { text: "Vigorous jazz hands.", type: "white" },
  { text: "Flightless birds.", type: "white" },
  { text: "Pictures of boobs.", type: "white" },
  { text: "Doing the right thing.", type: "white" },
  { text: "The violation of our most basic human rights.", type: "white" },
  { text: "Viagra®.", type: "white" },
  { text: "Self-loathing.", type: "white" },
  { text: "Spectacular abs.", type: "white" },
  { text: "A balanced breakfast.", type: "white" },
  { text: "Roofies.", type: "white" },
  { text: "Concealing a boner.", type: "white" },
  { text: "Amputees.", type: "white" },
  { text: "The Big Bang.", type: "white" },
  { text: "Former President George W. Bush.", type: "white" },
  { text: "The Rev. Dr. Martin Luther King, Jr.", type: "white" },
  { text: "Smegma.", type: "white" },
  { text: "Being marginalized.", type: "white" },
  { text: "Cuddling.", type: "white" },
  { text: "Laying an egg.", type: "white" },
  { text: "The Pope.", type: "white" },
  { text: "Aaron Burr.", type: "white" },
  { text: "Genghis Khan.", type: "white" },
  { text: "The south.", type: "white" },
  { text: "The guys from Queer Eye.", type: "white" },
  { text: "My humps.", type: "white" },
  { text: "The hardworking Mexican.", type: "white" },
  { text: "Agriculture.", type: "white" },
  { text: "Donald Trump's majestic golden mane.", type: "white" },
  { text: "A suspiciously shaped Among Us character.", type: "white" },
  { text: "Jeffrey Epstein's flight logs.", type: "white" },
  { text: "Adolf Hitler's missing testicle.", type: "white" },
  { text: "A thick, incomprehensible Scottish accent.", type: "white" },
  { text: "Unprotected sex with a stranger.", type: "white" },
  { text: "Being the Impostor and venting in front of everyone.", type: "white" },
  { text: "Donald Trump's tiny, tiny hands.", type: "white" },
  { text: "A sexy German accent.", type: "white" },
  { text: "The ghost of Jeffrey Epstein.", type: "white" },
  { text: "Unexpectedly getting an erection during a job interview.", type: "white" },
  { text: "Aggressive sexual healing.", type: "white" },
  { text: "Hiding in the vents like a little sussy baka.", type: "white" },
  { text: "A list of people who definitely weren't on that island.", type: "white" },
  { text: "Hitler's failed art career.", type: "white" },
  { text: "Drinking a warm glass of spit.", type: "white" },
  { text: "Elon Musk's latest child, named after a Wi-Fi password.", type: "white" },
  { text: "A slowly inflating inflatable doll.", type: "white" },
  { text: "Accidentally sending a dick pic to your grandma.", type: "white" },
  { text: "The existential dread of a Monday morning.", type: "white" },
  { text: "A lukewarm bowl of chunky milk.", type: "white" },
  { text: "Mark Zuckerberg's human-like blinking pattern.", type: "white" },
  { text: "The wet, slapping sound of a fish on pavement.", type: "white" },
  { text: "An industrial-sized vat of mayonnaise.", type: "white" },
  { text: "The crushing weight of student debt.", type: "white" },
  { text: "A collection of jars containing celebrity toenail clippings.", type: "white" },
  { text: "Passive-aggressive Post-it notes.", type: "white" },
  { text: "The specific smell of a damp basement.", type: "white" },
  { text: "A recursive loop of self-doubt.", type: "white" },
  { text: "The sound of a thousand kazoos playing 'My Heart Will Go On'.", type: "white" },
  { text: "What is the secret ingredient in the Krusty Krab's Krabby Patties?", type: "black", pick: 1 },
  { text: "The next big cryptocurrency will be based on _.", type: "black", pick: 1 },
  { text: "In a world without laws, the only thing that matters is _.", type: "black", pick: 1 },
  { text: "What's the most offensive thing you can say at a funeral?", type: "black", pick: 1 },
  { text: "Why is the internet so obsessed with _?", type: "black", pick: 1 },
  { text: "The new Marvel movie features a hero whose only power is _.", type: "black", pick: 1 },
  { text: "What is the real reason for the global supply chain crisis?", type: "black", pick: 1 },
  { text: "In the future, every home will be equipped with _.", type: "black", pick: 1 },
  { text: "What's the best way to get out of a speeding ticket?", type: "black", pick: 1 },
  { text: "The latest Silicon Valley trend is _.", type: "black", pick: 1 },
  { text: "What's the one thing that can stop a zombie apocalypse?", type: "black", pick: 1 },
  { text: "In my spare time, I enjoy _ while thinking about _.", type: "black", pick: 2 },
  { text: "What is the most awkward thing to find in your parents' bedroom?", type: "black", pick: 1 },
  { text: "The next big TikTok challenge involves _ and _.", type: "black", pick: 2 },
  { text: "What's the secret to a long and happy life?", type: "black", pick: 1 },
];
